import AppKit
import Foundation
import FifiCore
import ImageIO
import UniformTypeIdentifiers

@MainActor final class ClipboardMonitor {
    private let historyStore: HistoryStore
    private let blobStore: BlobStore
    private let ignoreRulesStore: IgnoreRulesStore
    private let settingsStore: SettingsStore
    private let storeQueue = DispatchQueue(label: "com.leafiy.fifi.clipboard-store", qos: .utility)

    // NSPasteboard has no change notifications; a 150 ms changeCount poll is
    // effectively free, so it needs no user-facing setting.
    private static let pollingInterval: TimeInterval = 0.15

    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount
    private var evaluator = IgnoreRuleEvaluator(ignoredBundleIDs: [], regexRules: [])

    init(historyStore: HistoryStore, blobStore: BlobStore, ignoreRulesStore: IgnoreRulesStore, settingsStore: SettingsStore) {
        self.historyStore = historyStore
        self.blobStore = blobStore
        self.ignoreRulesStore = ignoreRulesStore
        self.settingsStore = settingsStore
        reloadIgnoreRules()
    }

    func start() {
        guard timer == nil else { return }
        lastChangeCount = NSPasteboard.general.changeCount
        scheduleTimer()
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func reloadIgnoreRules() {
        do {
            let apps = try ignoreRulesStore.ignoredApps()
            let rules = try ignoreRulesStore.regexRules()
            evaluator = IgnoreRuleEvaluator(
                ignoredBundleIDs: Set(apps.map(\.bundleID)),
                regexRules: rules
            )
        } catch {
            NSLog("Fifi failed to reload ignore rules: %@", String(describing: error))
        }
    }


    private func scheduleTimer() {
        let interval = Self.pollingInterval
        let timer = Timer(timeInterval: interval, repeats: true) { [weak self] _ in
            Task { @MainActor in
                self?.pollPasteboard()
            }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    private func pollPasteboard() {
        let pasteboard = NSPasteboard.general
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount

        guard !settingsStore.settings.isRecordingPaused else {
            Self.log("recording paused; copy not captured")
            return
        }
        capture(from: pasteboard)
    }

    private func capture(from pasteboard: NSPasteboard) {
        let types = pasteboard.types ?? []
        guard !shouldSkip(types: types) else {
            Self.log("skipped self-write/transient pasteboard")
            return
        }

        let app = NSWorkspace.shared.frontmostApplication
        let sourceAppBundleID = app?.bundleIdentifier
        guard !evaluator.shouldIgnore(bundleID: sourceAppBundleID) else {
            Self.log("ignored copy from app \(sourceAppBundleID ?? "unknown")")
            return
        }

        let urls = fileURLs(from: pasteboard)
        let image = imagePayload(from: pasteboard)
        let candidate = CaptureCandidate(
            plainText: pasteboard.string(forType: .string),
            hasRichText: types.contains(.rtf),
            urlString: urlString(from: pasteboard, types: types),
            filePaths: urls.map(\.path),
            imageData: image?.data,
            imageUTI: image?.uti,
            imagePixelSize: image?.pixelSize,
            rawTypes: types.map(\.rawValue),
            sourceAppName: app?.localizedName,
            sourceAppBundleID: sourceAppBundleID
        )

        guard let classified = ClipboardClassifier.classify(candidate) else {
            Self.log("no usable content; types=\(types.map(\.rawValue).joined(separator: ","))")
            return
        }
        let textForIgnore = candidate.plainText ?? candidate.urlString
        guard !evaluator.shouldIgnore(text: textForIgnore) else {
            Self.log("ignored copy matching regex rule")
            return
        }

        persist(classified: classified, candidate: candidate)
    }

    private func shouldSkip(types: [NSPasteboard.PasteboardType]) -> Bool {
        let skippedTypes: Set<String> = [
            PasteboardWriter.markerType.rawValue,
            "org.nspasteboard.TransientType",
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.AutoGeneratedType"
        ]
        return types.contains { skippedTypes.contains($0.rawValue) }
    }

    private func persist(classified: ClassifiedCapture, candidate: CaptureCandidate) {
        let historyStore = historyStore
        let blobStore = blobStore

        storeQueue.async {
            do {
                let hash = ContentHash.sha256(classified.hashInput)
                var blobPath: String?
                var thumbnailPath: String?

                if classified.type == .image {
                    guard let imageData = candidate.imageData else {
                        NSLog("Fifi classified image capture without image data")
                        return
                    }
                    let ext = Self.imageExtension(for: candidate.imageUTI)
                    blobPath = try blobStore.storeBlob(imageData, hash: hash, fileExtension: ext)

                    guard let thumbnailData = Self.thumbnailPNGData(from: imageData) else {
                        NSLog("Fifi failed to create clipboard image thumbnail")
                        return
                    }
                    thumbnailPath = try blobStore.storeThumbnail(thumbnailData, hash: hash)
                } else if classified.needsTextBlob {
                    guard let text = classified.largeText, let data = text.data(using: .utf8) else {
                        NSLog("Fifi large text capture is missing UTF-8 data")
                        return
                    }
                    blobPath = try blobStore.storeBlob(data, hash: hash, fileExtension: "txt")
                }

                let item = NewClipboardItem(
                    contentHash: hash,
                    type: classified.type,
                    previewText: classified.previewText,
                    contentText: classified.contentText,
                    searchText: classified.searchText,
                    sourceAppName: candidate.sourceAppName,
                    sourceAppBundleID: candidate.sourceAppBundleID,
                    byteSize: classified.byteSize,
                    blobPath: blobPath,
                    thumbnailPath: thumbnailPath,
                    fileReference: classified.fileReference,
                    metadataJSON: classified.metadataJSON
                )
                let saved = try historyStore.save(item)
                Self.log("saved \(saved.type.rawValue) item id=\(saved.id) bytes=\(saved.byteSize)")
                DispatchQueue.main.async {
                    NotificationCenter.default.post(name: .fifiHistoryDidChange, object: nil)
                }
            } catch {
                NSLog("Fifi failed to persist clipboard capture: %@", String(describing: error))
            }
        }
    }

    private func fileURLs(from pasteboard: NSPasteboard) -> [URL] {
        // File URLs only: unrestricted NSURL pasteboard reading coerces plain
        // copied strings into URLs, misclassifying ordinary text.
        let options: [NSPasteboard.ReadingOptionKey: Any] = [.urlReadingFileURLsOnly: true]
        let objects = pasteboard.readObjects(forClasses: [NSURL.self], options: options) ?? []
        return objects.compactMap { object in
            if let url = object as? URL { return url }
            if let url = object as? NSURL { return url as URL }
            return nil
        }.filter(\.isFileURL)
    }

    private func urlString(from pasteboard: NSPasteboard, types: [NSPasteboard.PasteboardType]) -> String? {
        // Trust only an explicitly declared URL type; plain URL text is still
        // detected downstream by the classifier.
        guard types.contains(.URL) else { return nil }
        let value = pasteboard.string(forType: .URL)?.trimmingCharacters(in: .whitespacesAndNewlines)
        guard let value, !value.isEmpty else { return nil }
        return value
    }

    private func imagePayload(from pasteboard: NSPasteboard) -> (data: Data, uti: String, pixelSize: PixelSize?)? {
        if let data = pasteboard.data(forType: .png) {
            return (data, UTType.png.identifier, pixelSize(from: data))
        }

        guard let tiffData = pasteboard.data(forType: .tiff) else { return nil }
        let rep = NSBitmapImageRep(data: tiffData)
        let size = rep.map { PixelSize(width: $0.pixelsWide, height: $0.pixelsHigh) }
        if let pngData = rep?.representation(using: .png, properties: [:]) {
            return (pngData, UTType.png.identifier, size)
        }
        return (tiffData, UTType.tiff.identifier, size)
    }

    private func pixelSize(from data: Data) -> PixelSize? {
        guard let rep = NSBitmapImageRep(data: data) else { return nil }
        return PixelSize(width: rep.pixelsWide, height: rep.pixelsHigh)
    }

    private nonisolated static func imageExtension(for uti: String?) -> String {
        guard uti == UTType.tiff.identifier else { return "png" }
        return "tiff"
    }

    private nonisolated static func thumbnailPNGData(from data: Data) -> Data? {
        guard let source = CGImageSourceCreateWithData(data as CFData, nil) else { return nil }
        let options: [CFString: Any] = [
            kCGImageSourceCreateThumbnailFromImageIfAbsent: true,
            kCGImageSourceCreateThumbnailWithTransform: true,
            kCGImageSourceThumbnailMaxPixelSize: 240
        ]
        guard let image = CGImageSourceCreateThumbnailAtIndex(source, 0, options as CFDictionary) else { return nil }

        let thumbnailData = NSMutableData()
        guard let destination = CGImageDestinationCreateWithData(
            thumbnailData,
            UTType.png.identifier as CFString,
            1,
            nil
        ) else { return nil }
        CGImageDestinationAddImage(destination, image, nil)
        guard CGImageDestinationFinalize(destination) else { return nil }
        return thumbnailData as Data
    }

    private nonisolated static func log(_ message: String) {
        NSLog("Fifi[monitor] %@", message)
    }

    deinit {
        timer?.invalidate()
    }
}

extension Notification.Name {
    static let fifiHistoryDidChange = Notification.Name("com.leafiy.fifi.history-did-change")
}
